### ISSUE TITLE
MakeModel.py error

### ISSUE THREAD

**Issue by Kincaidr** [saopicc/DDFacet#27]
Hi,

I get the following error when running: MakeModel.py --BaseImageName=image_DD_nobeam_3poly --NCluster=3 after initial ddfacet run:

![image](https://user-images.githubusercontent.com/53697426/114300387-5f684780-9ac0-11eb-9efd-12c0ab76ffbc.png)

I showed a similar error to this in our Thursday meeting, i was told to switch to this alternate branch from: https://github.com/cyriltasse/DDFacet/tree/issue-690-691, which i have done here:

![image](https://user-images.githubusercontent.com/53697426/114300812-42cd0f00-9ac2-11eb-8206-e76950f1a5e1.png)

But i still get the above error.

Thanks for the help.

**Comment by bennahugo** [comment]
Please put your images and dicomodel somewhere for me to access (e.g. our
FTP server: elwood.ru.ac.za:/home/ftp-shares/pub/[youruser])

**Comment by Kincaidr** [comment]
Ok,I have copied the image: image_DD_nobeam_3poly.restored.fits and the DicoModel: image_DI_beam_2poly_beam_zwcl.DicoModel here: /net/elwood/home/ftp-shares/pub/kincaid

**Comment by bennahugo** [comment]
If I recall it also needs the norm images and dirty map. Could you copy all
the fits files to that directory. I will take a look tomorrow afternoon.

**Comment by Kincaidr** [comment]
I have copied them.
Thanks!

**Comment by bennahugo** [comment]
I cannot reproduce this issue. In fact looking at the error this is something I have fixed, by taking out the malformed shape specification in the mentioned branch. Are you sure you installed it with -e (or reinstalled it after checking out the branch)?
```
        if self.DoPlot:
            pylab.clf()
            pylab.scatter(x,y,c=indk,vmin=0,vmax=Nk,lw=0)
            pylab.scatter(xc,yc,c="black",marker="s")
            pylab.draw()
            pylab.show(block=False)
            pylab.pause(0.1)
```

**Comment by bennahugo** [comment]
Please retry your checkout and if you still run into the issue please reopen

**Comment by Kincaidr** [comment]
Now that you mention those install questions, i did not pip -e install after switching branch(using: git checkout -b issue-690-691). I have done so now in this new branch:

![image](https://user-images.githubusercontent.com/53697426/114456135-ce3ac300-9bdc-11eb-945d-964ebb1db9b6.png)

 but my error is still something similar:

![image](https://user-images.githubusercontent.com/53697426/114455115-a7c85800-9bdb-11eb-8e02-10fc82ac8b7e.png)

**Comment by bennahugo** [comment]
But wait this is a different error. You need to forward X to use this script because it plots with matplotlib

**Comment by Kincaidr** [comment]
I am not sure what is meant by: "to forward X".  Is this the X that allows plotting on server? If so,  this command is already in my local machine bashrc: alias crosby='ssh -XY kincaid@crosby.ru.ac.za'.

**Comment by bennahugo** [comment]
Well the DISPLAY variable is not set properly in this case, so there is something wrong with your forwarding (or you are running this in a screen). You have to run it outside a screen session with -YC set for your ssh session

**Comment by Kincaidr** [comment]
I was running in screen. I logged in with -YC with no screen. It works now:

![image](https://user-images.githubusercontent.com/53697426/114544202-9b371480-9c5a-11eb-99a1-c583accbeb85.png)
